version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - keycloak-network

  phpMyAdmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mysql
      PMA_PORT: "3306"
      PMA_ARBITRARY: 1
    ports:
      - "8180:80"
    depends_on:
      - mysql
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: xyz123ABC$
    ports:
      - "8080:8080"
    volumes:
      - ./import:/opt/keycloak/data/import
    depends_on:
      - mysql
    networks:
      - keycloak-network

volumes:
  mysql_data:

networks:
  keycloak-network:
